import { writeFile } from 'node:fs/promises'
import path from 'node:path'

import { getCommissionDataMap } from '#data/commissionData'
import { getCharacterRecords } from '#data/commissionRecords'
import { getCreatorAliasesMap, normalizeCreatorSearchName } from '#data/creatorAliases'
import { parseCommissionFileName } from '#lib/commissions/index'
import { buildDateSearchTokensFromCompactDate } from '#lib/date/search'

type SearchEntry = {
  id: number
  searchText: string
  searchSuggest: string
}

const normalizeSuggestionKey = (term: string) => term.trim().toLowerCase()

const buildHomeSearchEntries = (): SearchEntry[] => {
  const records = getCharacterRecords()
  const commissionMap = getCommissionDataMap()
  const creatorAliasesMap = getCreatorAliasesMap()
  const orderedCharacters = [
    ...records.filter(record => record.status === 'active').map(record => record.name),
    ...records.filter(record => record.status === 'stale').map(record => record.name),
  ]
  const entries: SearchEntry[] = []
  let nextId = 0

  for (const characterName of orderedCharacters) {
    const commissions = commissionMap.get(characterName)?.Commissions ?? []

    for (const commission of commissions) {
      const { date, year, creator } = parseCommissionFileName(commission.fileName)
      const month = date.slice(4, 6)
      const normalizedCreatorName = creator ? normalizeCreatorSearchName(creator) : null
      const creatorAliases = normalizedCreatorName
        ? (creatorAliasesMap.get(normalizedCreatorName) ?? [])
        : []
      const searchableDateTerms = [date, ...buildDateSearchTokensFromCompactDate(date)]
      const keywordTerms = (commission.Keyword ?? '')
        .split(/[,\n，、;；]/)
        .map(keyword => keyword.trim())
        .filter(Boolean)
      const keywordSearchText = keywordTerms.join(' ')

      const suggestionEntries = [
        { source: 'Character', term: characterName },
        { source: 'Date', term: `${year}/${month}` },
        ...(normalizedCreatorName
          ? [{ source: 'Creator' as const, term: normalizedCreatorName }]
          : []),
        ...creatorAliases.map(alias => ({ source: 'Creator' as const, term: alias })),
        ...keywordTerms.map(keyword => ({ source: 'Keyword' as const, term: keyword })),
      ]

      const uniqueSuggestions = new Map<string, { source: string; term: string }>()
      for (const entry of suggestionEntries) {
        const normalizedTerm = normalizeSuggestionKey(entry.term)
        if (!normalizedTerm || uniqueSuggestions.has(normalizedTerm)) continue
        uniqueSuggestions.set(normalizedTerm, entry)
      }

      const searchSuggest = [...uniqueSuggestions.values()]
        .map(entry => `${entry.source}\t${entry.term}`)
        .join('\n')

      const searchText = [
        characterName,
        normalizedCreatorName,
        ...creatorAliases,
        ...searchableDateTerms,
        commission.Design ?? '',
        commission.Description ?? '',
        keywordSearchText,
      ]
        .join(' ')
        .toLowerCase()

      entries.push({
        id: nextId,
        searchText,
        searchSuggest,
      })
      nextId += 1
    }
  }

  return entries
}

const outputPath = path.join(
  process.cwd(),
  'app',
  'components',
  'home',
  'search',
  'homeSearchEntries.generated.ts',
)

const entries = buildHomeSearchEntries()

const file = `// Auto-generated by scripts/homeSearchEntries.ts
// Do not edit manually.

export const homeSearchEntries = ${JSON.stringify(entries, null, 2)}
`

await writeFile(outputPath, file)
console.log(
  `Generated ${entries.length} home search entries -> ${path.relative(process.cwd(), outputPath)}`,
)
